export const PAGES = {
  home: '/',
  about: '/about',
  team: '/team',
  contacts: '/contacts',
  checkout: '/checkout',
  productsCategory: '/products/:categoryName',
  productDetailsPage: '/products/:categoryName/:id',
  productsAll: '/products/all',
  productsCakes: '/products/cakes',
  productsPresents: '/products/presents',
  productsEaster: '/products/easter',
  shop: 'shop',
  shipping: '/shipping',
  questions: '/questions',
  aboutZefir: '/about-zefir',
  aboutPayment: '/about-payment',
  payment: '/payment',
  confirmation: '/confirmation',
}
