export const PAGES = {
  home: `/`,
  contacts: `/contacts`,
  checkout: `/checkout`,
  confirmation: `/confirmation`,
  payment: `payment`,
  productsCategory: `/products/:categoryName`,
  productDetailsPage: `/products/:categoryName/:id`,
  productsAll: `/products/all`,
  productsCakes: `/products/cakes`,
  productsPresents: `/products/presents`,
  productsEaster: `/products/easter`,
  shop: `shop`,
  shipping: `shipping`,
  aboutZefir: `aboutZefir`,
  aboutPayment: `aboutPayment`,
  about: `about`,
  team: `team`,
}
